name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build & Push Image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.selcloud.ru
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Build, Tag and Push
        run: |
          docker build --file Dockerfile -t cr.selcloud.ru/${{ github.repository }}:${{ github.sha }} . \
          && docker tag cr.selcloud.ru/${{ github.repository }}:${{ github.sha }} cr.selcloud.ru/${{ github.repository }}:latest \
          && docker tag cr.selcloud.ru/${{ github.repository }}:${{ github.sha }} cr.selcloud.ru/${{ github.repository }}:${{ github.run_number }} \
          && docker push cr.selcloud.ru/${{ github.repository }}:${{ github.run_number }} \
          && docker push cr.selcloud.ru/${{ github.repository }}:latest
